import {modes} from './constants';

const ops6809 = [
  {op: 0x00, mnem: 'NEG', page: 0, mode: modes.direct, code: 'drct;ftch8;neg8;stor8'},
  {op: 0x01, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x02, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x03, mnem: 'COM', page: 0, mode: modes.direct, code: 'drct;ftch8;com8;stor8'},
  {op: 0x04, mnem: 'LSR', page: 0, mode: modes.direct, code: 'drct;ftch8;lsr8;stor8'},
  {op: 0x05, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x06, mnem: 'ROR', page: 0, mode: modes.direct, code: 'drct;ftch8;ror8;stor8'},
  {op: 0x07, mnem: 'ASR', page: 0, mode: modes.direct, code: 'drct;ftch8;asr8;stor8'},
  {op: 0x08, mnem: 'LSL', page: 0, mode: modes.direct, code: 'drct;ftch8;lsl8;stor8'},
  {op: 0x08, mnem: 'ASL', page: 0, mode: modes.direct, code: 'drct;ftch8;lsl8;stor8'},
  {op: 0x09, mnem: 'ROL', page: 0, mode: modes.direct, code: 'drct;ftch8;rol8;stor8'},
  {op: 0x0A, mnem: 'DEC', page: 0, mode: modes.direct, code: 'drct;ftch8;dec8;stor8'},
  {op: 0x0B, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x0C, mnem: 'INC', page: 0, mode: modes.direct, code: 'drct;ftch8;inc8;stor8'},
  {op: 0x0D, mnem: 'TST', page: 0, mode: modes.direct, code: 'drct;ftch8;tst8;stor8'},
  {op: 0x0E, mnem: 'JMP', page: 0, mode: modes.direct, code: 'drct;ea1;st1 regPC;ntck'},
  {op: 0x0F, mnem: 'CLR', page: 0, mode: modes.direct, code: 'drct;ftch8;clr8;stor8'},

  {op: 0x10, mnem: '', page: 0, mode: modes.simple | modes.pager, code: 'page 0x10'},
  {op: 0x11, mnem: '', page: 0, mode: modes.simple | modes.pager, code: 'page 0x11'},
  {op: 0x12, mnem: 'NOP', page: 0, mode: modes.simple, code: 'nop'},
  {op: 0x13, mnem: 'SYNC', page: 0, mode: modes.simple, code: 'sync'},
  {op: 0x14, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x15, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x16, mnem: 'LBRA', page: 0, mode: modes.pcr | modes.bits16, code: 'rel16;st1 regPC;ntck'},
  {op: 0x17, mnem: 'LBSR', page: 0, mode: modes.pcr | modes.bits16, code: 'rel16;stck16 regPC;st1 regPC;ntck'},
  {op: 0x18, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x19, mnem: 'DAA', page: 0, mode: modes.simple, code: 'daa'},
  {op: 0x1A, mnem: 'ORCC', page: 0, mode: modes.immediate, code: 'pcb;ld2 regCC;exx;or8;st1 regCC'},
  {op: 0x1B, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x1C, mnem: 'ANDCC', page: 0, mode: modes.immediate, code: 'pcb;ld2 regCC;exx;and8;st1 regCC'},
  {op: 0x1D, mnem: 'SEX', page: 0, mode: modes.simple, code: 'ld1 regB;sx;shft;st1 regA'},
  {op: 0x1E, mnem: 'EXG', page: 0, mode: modes.register | modes.pair, code: 'rgop exg'},
  {op: 0x1F, mnem: 'TFR', page: 0, mode: modes.register | modes.pair, code: 'rgop tfr'},

  {op: 0x20, mnem: 'BRA', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;st1 regPC;ntck'},
  {op: 0x21, mnem: 'BRN', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8'},
  {op: 0x22, mnem: 'BHI', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk LS;qt;st1 regPC;ntck'},
  {op: 0x23, mnem: 'BLS', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk LS;qf;st1 regPC;ntck'},
  {op: 0x24, mnem: 'BCC', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk C;qt;st1 regPC;ntck'},
  {op: 0x24, mnem: 'BHS', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk C;qt;st1 regPC;ntck'},
  {op: 0x25, mnem: 'BCS', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk C;qf;st1 regPC;ntck'},
  {op: 0x25, mnem: 'BLO', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk C;qf;st1 regPC;ntck'},
  {op: 0x26, mnem: 'BNE', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk Z;qt;st1 regPC;ntck'},
  {op: 0x27, mnem: 'BEQ', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk Z;qf;st1 regPC;ntck'},
  {op: 0x28, mnem: 'BVC', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk V;qt;st1 regPC;ntck'},
  {op: 0x29, mnem: 'BVS', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk V;qf;st1 regPC;ntck'},
  {op: 0x2A, mnem: 'BMI', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk N;qf;st1 regPC;ntck'},
  {op: 0x2B, mnem: 'BPL', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk N;qt;st1 regPC;ntck'},
  {op: 0x2C, mnem: 'BGE', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk LT;qt;st1 regPC;ntck'},
  {op: 0x2D, mnem: 'BLT', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk LT;qf;st1 regPC;ntck'},
  {op: 0x2E, mnem: 'BGT', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk LE;qt;st1 regPC;ntck'},
  {op: 0x2F, mnem: 'BLE', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;chk LE;qf;st1 regPC;ntck'},

  {op: 0x20, mnem: 'LBRA', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;st1 regPC;ntck'},
  {op: 0x21, mnem: 'LBRN', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16'},
  {op: 0x22, mnem: 'LBHI', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk LS;qt;st1 regPC;ntck'},
  {op: 0x23, mnem: 'LBLS', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk LS;qf;st1 regPC;ntck'},
  {op: 0x24, mnem: 'LBCC', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk C;qt;st1 regPC;ntck'},
  {op: 0x24, mnem: 'LBHS', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk C;qt;st1 regPC;ntck'},
  {op: 0x25, mnem: 'LBCS', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk C;qf;st1 regPC;ntck'},
  {op: 0x25, mnem: 'LBLO', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk C;qf;st1 regPC;ntck'},
  {op: 0x26, mnem: 'LBNE', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk Z;qt;st1 regPC;ntck'},
  {op: 0x27, mnem: 'LBEQ', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk Z;qf;st1 regPC;ntck'},
  {op: 0x28, mnem: 'LBVC', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk V;qt;st1 regPC;ntck'},
  {op: 0x29, mnem: 'LBVS', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk V;qf;st1 regPC;ntck'},
  {op: 0x2A, mnem: 'LBMI', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk N;qf;st1 regPC;ntck'},
  {op: 0x2B, mnem: 'LBPL', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk N;qt;st1 regPC;ntck'},
  {op: 0x2C, mnem: 'LBGE', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk LT;qt;st1 regPC;ntck'},
  {op: 0x2D, mnem: 'LBLT', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk LT;qf;st1 regPC;ntck'},
  {op: 0x2E, mnem: 'LBGT', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk LE;qt;st1 regPC;ntck'},
  {op: 0x2F, mnem: 'LBLE', page: 0x10, mode: modes.pcr | modes.bits16, code: 'rel16;chk LE;qf;st1 regPC;ntck'},

  {op: 0x30, mnem: 'LEAX', page: 0, mode: modes.indexed, code: 'indx;ea1;zero;idxu;st1 regX'},
  {op: 0x31, mnem: 'LEAY', page: 0, mode: modes.indexed, code: 'indx;ea1;zero;idxu;st1 regY'},
  {op: 0x32, mnem: 'LEAS', page: 0, mode: modes.indexed, code: 'indx;ea1;idxu;st1 regS'},
  {op: 0x33, mnem: 'LEAU', page: 0, mode: modes.indexed, code: 'indx;ea1;idxu;st1 regU'},
  {op: 0x34, mnem: 'PSHS', page: 0, mode: modes.register, code: 'push regS'},
  {op: 0x35, mnem: 'PULS', page: 0, mode: modes.register, code: 'pull regS'},
  {op: 0x36, mnem: 'PSHU', page: 0, mode: modes.register, code: 'push regU'},
  {op: 0x37, mnem: 'PULU', page: 0, mode: modes.register, code: 'pull regU'},
  {op: 0x38, mnem: 'ERR', page: 0, mode: modes.direct, code: 'err'},
  {op: 0x39, mnem: 'RTS', page: 0, mode: modes.simple, code: 'pull16 regS;st1 regPC;ntck'},
  {op: 0x3A, mnem: 'ABX', page: 0, mode: modes.simple, code: 'abx'},
  {op: 0x3B, mnem: 'RTI', page: 0, mode: modes.simple, code: 'rti;ntck'},
  {op: 0x3C, mnem: 'CWAI', page: 0, mode: modes.immediate, code: 'pcb;ld2 regCC;exx;and8;wait'},
  {op: 0x3D, mnem: 'MUL', page: 0, mode: modes.simple, code: 'mul'},
  {op: 0x3E, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x3F, mnem: 'SWI', page: 0, mode: modes.simple, code: 'swi 1'},
  {op: 0x3F, mnem: 'SWI2', page: 0x10, mode: modes.simple, code: 'swi 2'},
  {op: 0x3F, mnem: 'SWI3', page: 0x11, mode: modes.simple, code: 'swi 3'},

  {op: 0x40, mnem: 'NEGA', page: 0, mode: modes.simple, code: 'ld1 regA;neg8;st1 regA'},
  {op: 0x41, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x42, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x43, mnem: 'COMA', page: 0, mode: modes.simple, code: 'ld1 regA;com8;st1 regA'},
  {op: 0x44, mnem: 'LSRA', page: 0, mode: modes.simple, code: 'ld1 regA;lsr8;st1 regA'},
  {op: 0x45, mnem: 'ERRA', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x46, mnem: 'RORA', page: 0, mode: modes.simple, code: 'ld1 regA;ror8;st1 regA'},
  {op: 0x47, mnem: 'ASRA', page: 0, mode: modes.simple, code: 'ld1 regA;asr8;st1 regA'},
  {op: 0x48, mnem: 'LSLA', page: 0, mode: modes.simple, code: 'ld1 regA;lsl8;st1 regA'},
  {op: 0x48, mnem: 'ASLA', page: 0, mode: modes.simple, code: 'ld1 regA;lsl8;st1 regA'},
  {op: 0x49, mnem: 'ROLA', page: 0, mode: modes.simple, code: 'ld1 regA;rol8;st1 regA'},
  {op: 0x4A, mnem: 'DECA', page: 0, mode: modes.simple, code: 'ld1 regA;dec8;st1 regA'},
  {op: 0x4B, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x4C, mnem: 'INCA', page: 0, mode: modes.simple, code: 'ld1 regA;inc8;st1 regA'},
  {op: 0x4D, mnem: 'TSTA', page: 0, mode: modes.simple, code: 'ld1 regA;tst8;st1 regA'},
  {op: 0x4E, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x4F, mnem: 'CLRA', page: 0, mode: modes.simple, code: 'ld1 regA;clr8;st1 regA'},

  {op: 0x50, mnem: 'NEGB', page: 0, mode: modes.simple, code: 'ld1 regB;neg8;st1 regB'},
  {op: 0x51, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x52, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x53, mnem: 'COMB', page: 0, mode: modes.simple, code: 'ld1 regB;com8;st1 regB'},
  {op: 0x54, mnem: 'LSRB', page: 0, mode: modes.simple, code: 'ld1 regB;lsr8;st1 regB'},
  {op: 0x55, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x56, mnem: 'RORB', page: 0, mode: modes.simple, code: 'ld1 regB;ror8;st1 regB'},
  {op: 0x57, mnem: 'ASRB', page: 0, mode: modes.simple, code: 'ld1 regB;asr8;st1 regB'},
  {op: 0x58, mnem: 'LSLB', page: 0, mode: modes.simple, code: 'ld1 regB;lsl8;st1 regB'},
  {op: 0x58, mnem: 'ASLB', page: 0, mode: modes.simple, code: 'ld1 regB;lsl8;st1 regB'},
  {op: 0x59, mnem: 'ROLB', page: 0, mode: modes.simple, code: 'ld1 regB;rol8;st1 regB'},
  {op: 0x5A, mnem: 'DECB', page: 0, mode: modes.simple, code: 'ld1 regB;dec8;st1 regB'},
  {op: 0x5B, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x5C, mnem: 'INCB', page: 0, mode: modes.simple, code: 'ld1 regB;inc8;st1 regB'},
  {op: 0x5D, mnem: 'TSTB', page: 0, mode: modes.simple, code: 'ld1 regB;tst8;st1 regB'},
  {op: 0x5E, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0x5F, mnem: 'CLRB', page: 0, mode: modes.simple, code: 'ld1 regB;clr8;st1 regB'},

  {op: 0x60, mnem: 'NEG', page: 0, mode: modes.indexed, code: 'indx;ftch8;neg8;stor8;idxu'},
  {op: 0x61, mnem: 'ERR', page: 0, mode: modes.indexed, code: 'err'},
  {op: 0x62, mnem: 'ERR', page: 0, mode: modes.indexed, code: 'err'},
  {op: 0x63, mnem: 'COM', page: 0, mode: modes.indexed, code: 'indx;ftch8;com8;stor8;idxu'},
  {op: 0x64, mnem: 'LSR', page: 0, mode: modes.indexed, code: 'indx;ftch8;lsr8;stor8;idxu'},
  {op: 0x65, mnem: 'ERR', page: 0, mode: modes.indexed, code: 'err'},
  {op: 0x66, mnem: 'ROR', page: 0, mode: modes.indexed, code: 'indx;ftch8;ror8;stor8;idxu'},
  {op: 0x67, mnem: 'ASR', page: 0, mode: modes.indexed, code: 'indx;ftch8;asr8;stor8;idxu'},
  {op: 0x68, mnem: 'LSL', page: 0, mode: modes.indexed, code: 'indx;ftch8;lsl8;stor8;idxu'},
  {op: 0x68, mnem: 'ASL', page: 0, mode: modes.indexed, code: 'indx;ftch8;lsl8;stor8;idxu'},
  {op: 0x69, mnem: 'ROL', page: 0, mode: modes.indexed, code: 'indx;ftch8;rol8;stor8;idxu'},
  {op: 0x6A, mnem: 'DEC', page: 0, mode: modes.indexed, code: 'indx;ftch8;dec8;stor8;idxu'},
  {op: 0x6B, mnem: 'ERR', page: 0, mode: modes.indexed, code: 'err'},
  {op: 0x6C, mnem: 'INC', page: 0, mode: modes.indexed, code: 'indx;ftch8;inc8;stor8;idxu'},
  {op: 0x6D, mnem: 'TST', page: 0, mode: modes.indexed, code: 'indx;ftch8;tst8;stor8;idxu'},
  {op: 0x6E, mnem: 'JMP', page: 0, mode: modes.indexed, code: 'indx;ea1;st1 regPC;idxu;ntck'},
  {op: 0x6F, mnem: 'CLR', page: 0, mode: modes.indexed, code: 'indx;ftch8;clr8;stor8;idxu'},

  {op: 0x70, mnem: 'NEG', page: 0, mode: modes.extended, code: 'xtnd;ftch8;neg8;stor8'},
  {op: 0x71, mnem: 'ERR', page: 0, mode: modes.extended, code: 'err'},
  {op: 0x72, mnem: 'ERR', page: 0, mode: modes.extended, code: 'err'},
  {op: 0x73, mnem: 'COM', page: 0, mode: modes.extended, code: 'xtnd;ftch8;com8;stor8'},
  {op: 0x74, mnem: 'LSR', page: 0, mode: modes.extended, code: 'xtnd;ftch8;lsr8;stor8'},
  {op: 0x75, mnem: 'ERR', page: 0, mode: modes.extended, code: 'err'},
  {op: 0x76, mnem: 'ROR', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ror8;stor8'},
  {op: 0x77, mnem: 'ASR', page: 0, mode: modes.extended, code: 'xtnd;ftch8;asr8;stor8'},
  {op: 0x78, mnem: 'LSL', page: 0, mode: modes.extended, code: 'xtnd;ftch8;lsl8;stor8'},
  {op: 0x78, mnem: 'ASL', page: 0, mode: modes.extended, code: 'xtnd;ftch8;lsl8;stor8'},
  {op: 0x79, mnem: 'ROL', page: 0, mode: modes.extended, code: 'xtnd;ftch8;rol8;stor8'},
  {op: 0x7A, mnem: 'DEC', page: 0, mode: modes.extended, code: 'xtnd;ftch8;dec8;stor8'},
  {op: 0x7B, mnem: 'ERR', page: 0, mode: modes.extended, code: 'err'},
  {op: 0x7C, mnem: 'INC', page: 0, mode: modes.extended, code: 'xtnd;ftch8;inc8;stor8'},
  {op: 0x7D, mnem: 'TST', page: 0, mode: modes.extended, code: 'xtnd;ftch8;tst8;stor8'},
  {op: 0x7E, mnem: 'JMP', page: 0, mode: modes.extended, code: 'xtnd;ea1;st1 regPC;ntck'},
  {op: 0x7F, mnem: 'CLR', page: 0, mode: modes.extended, code: 'xtnd;ftch8;clr8;stor8'},

  {op: 0x80, mnem: 'SUBA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;sub8;st1 regA'},
  {op: 0x81, mnem: 'CMPA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;sub8'},
  {op: 0x82, mnem: 'SBCA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;sbc8;st1 regA'},
  {op: 0x83, mnem: 'SUBD', page: 0, mode: modes.immediate | modes.bits16, code: 'pcw;ld2 regD;sub16;st1 regD'},
  {op: 0x83, mnem: 'CMPD', page: 0x10, mode: modes.immediate | modes.bits16, code: 'pcw;ld2 regD;sub16'},
  {op: 0x83, mnem: 'CMPU', page: 0x11, mode: modes.immediate | modes.bits16, code: 'pcw;ld2 regU;sub16'},
  {op: 0x84, mnem: 'ANDA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;and8;st1 regA'},
  {op: 0x85, mnem: 'BITA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;and8'},
  {op: 0x86, mnem: 'LDA', page: 0, mode: modes.immediate, code: 'pcb;tst8; st1 regA'},
  {op: 0x87, mnem: 'ERR', page: 0, mode: modes.immediate, code: 'err'},
  {op: 0x88, mnem: 'EORA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;eor8;st1 regA'},
  {op: 0x89, mnem: 'ADCA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;adc8;st1 regA'},
  {op: 0x8A, mnem: 'ORA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;or8;st1 regA'},
  {op: 0x8B, mnem: 'ADDA', page: 0, mode: modes.immediate, code: 'pcb;ld2 regA;add8;st1 regA'},
  {op: 0x8C, mnem: 'CMPX', page: 0, mode: modes.immediate | modes.bits16, code: 'pcw;ld2 regX;sub16'},
  {op: 0x8C, mnem: 'CMPY', page: 0x10, mode: modes.immediate | modes.bits16, code: 'pcw;ld2 regY;sub16'},
  {op: 0x8C, mnem: 'CMPS', page: 0x11, mode: modes.immediate | modes.bits16, code: 'pcw;ld2 regS;sub16'},
  {op: 0x8D, mnem: 'BSR', page: 0, mode: modes.pcr | modes.bits8, code: 'rel8;stck16 regPC;st1 regPC;ntck'},
  {op: 0x8E, mnem: 'LDX', page: 0, mode: modes.immediate | modes.bits16, code: 'pcw;tst16;st1 regX'},
  {op: 0x8E, mnem: 'LDY', page: 0x10, mode: modes.immediate | modes.bits16, code: 'pcw;tst16;st1 regY'},
  {op: 0x8F, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},

  {op: 0x90, mnem: 'SUBA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;sub8;st1 regA'},
  {op: 0x91, mnem: 'CMPA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;sub8'},
  {op: 0x92, mnem: 'SBCA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;sbc8;st1 regA'},
  {op: 0x93, mnem: 'SUBD', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ftch16;ld2 regD;sub16;st1 regD'},
  {op: 0x93, mnem: 'CMPD', page: 0x10, mode: modes.direct | modes.bits16, code: 'drct;ftch16;ld2 regD;sub16'},
  {op: 0x93, mnem: 'CMPU', page: 0x11, mode: modes.direct | modes.bits16, code: 'drct;ftch16;ld2 regU;sub16'},
  {op: 0x94, mnem: 'ANDA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;and8;st1 regA'},
  {op: 0x95, mnem: 'BITA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;and8'},
  {op: 0x96, mnem: 'LDA', page: 0, mode: modes.direct, code: 'drct;ftch8;tst8; st1 regA'},
  {op: 0x97, mnem: 'STA', page: 0, mode: modes.direct, code: 'drct;ld1 regA;tst8;stor8'},
  {op: 0x98, mnem: 'EORA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;eor8;st1 regA'},
  {op: 0x99, mnem: 'ADCA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;adc8;st1 regA'},
  {op: 0x9A, mnem: 'ORA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;or8;st1 regA'},
  {op: 0x9B, mnem: 'ADDA', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regA;add8;st1 regA'},
  {op: 0x9C, mnem: 'CMPX', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ftch16;ld2 regX;sub16'},
  {op: 0x9C, mnem: 'CMPY', page: 0x10, mode: modes.direct | modes.bits16, code: 'drct;ftch16;ld2 regY;sub16'},
  {op: 0x9C, mnem: 'CMPS', page: 0x11, mode: modes.direct | modes.bits16, code: 'drct;ftch16;ld2 regS;sub16'},
  {op: 0x9D, mnem: 'JSR', page: 0, mode: modes.direct | modes.bits16, code: 'drct;stck16 regPC;ea1;st1 regPC;ntck'},
  {op: 0x9E, mnem: 'LDX', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ftch16;tst16;st1 regX'},
  {op: 0x9E, mnem: 'LDY', page: 0x10, mode: modes.direct | modes.bits16, code: 'drct;ftch16;tst16;st1 regY'},
  {op: 0x9F, mnem: 'STX', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ld1 regX;tst16;stor16'},
  {op: 0x9F, mnem: 'STY', page: 0x10, mode: modes.direct | modes.bits16, code: 'drct;ld1 regY;tst16;stor16'},

  {op: 0xA0, mnem: 'SUBA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;sub8;idxu;st1 regA'},
  {op: 0xA1, mnem: 'CMPA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;sub8;idxu'},
  {op: 0xA2, mnem: 'SBCA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;sbc8;idxu;st1 regA'},
  {
    op: 0xA3,
    mnem: 'SUBD',
    page: 0,
    mode: modes.indexed | modes.bits16,
    code: 'indx;ftch16;ld2 regD;sub16;idxu;st1 regD',
  },
  {op: 0xA3, mnem: 'CMPD', page: 0x10, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;ld2 regD;sub16;idxu'},
  {op: 0xA3, mnem: 'CMPU', page: 0x11, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;ld2 regU;sub16;idxu'},
  {op: 0xA4, mnem: 'ANDA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;and8;idxu;st1 regA'},
  {op: 0xA5, mnem: 'BITA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;and8;idxu'},
  {op: 0xA6, mnem: 'LDA', page: 0, mode: modes.indexed, code: 'indx;ftch8;tst8;idxu;st1 regA'},
  {op: 0xA7, mnem: 'STA', page: 0, mode: modes.indexed, code: 'indx;ld1 regA;tst8;stor8;idxu'},
  {op: 0xA8, mnem: 'EORA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;eor8;idxu;st1 regA'},
  {op: 0xA9, mnem: 'ADCA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;adc8;idxu;st1 regA'},
  {op: 0xAA, mnem: 'ORA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;or8;idxu;st1 regA'},
  {op: 0xAB, mnem: 'ADDA', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regA;add8;idxu;st1 regA'},
  {op: 0xAC, mnem: 'CMPX', page: 0, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;ld2 regX;sub16;idxu'},
  {op: 0xAC, mnem: 'CMPY', page: 0x10, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;ld2 regY;sub16;idxu'},
  {op: 0xAC, mnem: 'CMPS', page: 0x11, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;ld2 regS;sub16;idxu'},
  {
    op: 0xAD,
    mnem: 'JSR',
    page: 0,
    mode: modes.indexed | modes.bits16,
    code: 'indx;idxu;stck16 regPC;ea1;st1 regPC;ntck',
  },
  {op: 0xAE, mnem: 'LDX', page: 0, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;tst16;st1 regX;idxu'},
  {op: 0xAE, mnem: 'LDY', page: 0x10, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;tst16;st1 regY;idxu'},
  {op: 0xAF, mnem: 'STX', page: 0, mode: modes.indexed | modes.bits16, code: 'indx;ld1 regX;tst16;stor16;idxu'},
  {op: 0xAF, mnem: 'STY', page: 0x10, mode: modes.indexed | modes.bits16, code: 'indx;ld1 regY;tst16;stor16;idxu'},

  {op: 0xB0, mnem: 'SUBA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;sub8;st1 regA'},
  {op: 0xB1, mnem: 'CMPA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;sub8'},
  {op: 0xB2, mnem: 'SBCA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;sbc8;st1 regA'},
  {op: 0xB3, mnem: 'SUBD', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;ld2 regD;sub16;st1 regD'},
  {op: 0xB3, mnem: 'CMPD', page: 0x10, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;ld2 regD;sub16'},
  {op: 0xB3, mnem: 'CMPU', page: 0x11, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;ld2 regU;sub16'},
  {op: 0xB4, mnem: 'ANDA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;and8;st1 regA'},
  {op: 0xB5, mnem: 'BITA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;and8'},
  {op: 0xB6, mnem: 'LDA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;tst8; st1 regA'},
  {op: 0xB7, mnem: 'STA', page: 0, mode: modes.extended, code: 'xtnd;ld1 regA;tst8;stor8'},
  {op: 0xB8, mnem: 'EORA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;eor8;st1 regA'},
  {op: 0xB9, mnem: 'ADCA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;adc8;st1 regA'},
  {op: 0xBA, mnem: 'ORA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;or8;st1 regA'},
  {op: 0xBB, mnem: 'ADDA', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regA;add8;st1 regA'},
  {op: 0xBC, mnem: 'CMPX', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;ld2 regX;sub16'},
  {op: 0xBC, mnem: 'CMPY', page: 0x10, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;ld2 regY;sub16'},
  {op: 0xBC, mnem: 'CMPS', page: 0x11, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;ld2 regS;sub16'},
  {op: 0xBD, mnem: 'JSR', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;stck16 regPC;ea1;st1 regPC;ntck'},
  {op: 0xBE, mnem: 'LDX', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;tst16;st1 regX'},
  {op: 0xBE, mnem: 'LDY', page: 0x10, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;tst16;st1 regY'},
  {op: 0xBF, mnem: 'STX', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ld1 regX;tst16;stor16'},
  {op: 0xBF, mnem: 'STY', page: 0x10, mode: modes.extended | modes.bits16, code: 'xtnd;ld1 regY;tst16;stor16'},

  {op: 0xC0, mnem: 'SUBB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;sub8;st1 regB'},
  {op: 0xC1, mnem: 'CMPB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;sub8'},
  {op: 0xC2, mnem: 'SBCB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;sbc8;st1 regB'},
  {op: 0xC3, mnem: 'ADDD', page: 0, mode: modes.immediate | modes.bits16, code: 'pcw;ld2 regD;add16;st1 regD'},
  {op: 0xC4, mnem: 'ANDB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;and8;st1 regB'},
  {op: 0xC5, mnem: 'BITB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;and8'},
  {op: 0xC6, mnem: 'LDB', page: 0, mode: modes.immediate, code: 'pcb;tst8; st1 regB'},
  {op: 0xC7, mnem: 'ERR', page: 0, mode: modes.immediate, code: 'err'},
  {op: 0xC8, mnem: 'EORB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;eor8;st1 regB'},
  {op: 0xC9, mnem: 'ADCB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;adc8;st1 regB'},
  {op: 0xCA, mnem: 'ORB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;or8;st1 regB'},
  {op: 0xCB, mnem: 'ADDB', page: 0, mode: modes.immediate, code: 'pcb;ld2 regB;add8;st1 regB'},
  {op: 0xCC, mnem: 'LDD', page: 0, mode: modes.immediate | modes.bits16, code: 'pcw;tst16;st1 regD'},
  {op: 0xCD, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},
  {op: 0xCE, mnem: 'LDU', page: 0, mode: modes.immediate | modes.bits16, code: 'pcw;tst16;st1 regU'},
  {op: 0xCE, mnem: 'LDS', page: 0x10, mode: modes.immediate | modes.bits16, code: 'pcw;tst16;st1 regS'},
  {op: 0xCF, mnem: 'ERR', page: 0, mode: modes.simple, code: 'err'},

  {op: 0xD0, mnem: 'SUBB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;sub8;st1 regB'},
  {op: 0xD1, mnem: 'CMPB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;sub8'},
  {op: 0xD2, mnem: 'SBCB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;sbc8;st1 regB'},
  {op: 0xD3, mnem: 'ADDD', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ftch16;ld2 regD;add16;st1 regD'},
  {op: 0xD4, mnem: 'ANDB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;and8;st1 regB'},
  {op: 0xD5, mnem: 'BITB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;and8'},
  {op: 0xD6, mnem: 'LDB', page: 0, mode: modes.direct, code: 'drct;ftch8;tst8; st1 regB'},
  {op: 0xD7, mnem: 'STB', page: 0, mode: modes.direct, code: 'drct;ld1 regB;tst8;stor8'},
  {op: 0xD8, mnem: 'EORB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;eor8;st1 regB'},
  {op: 0xD9, mnem: 'ADCB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;adc8;st1 regB'},
  {op: 0xDA, mnem: 'ORB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;or8;st1 regB'},
  {op: 0xDB, mnem: 'ADDB', page: 0, mode: modes.direct, code: 'drct;ftch8;ld2 regB;add8;st1 regB'},
  {op: 0xDC, mnem: 'LDD', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ftch16;tst16;st1 regD'},
  {op: 0xDD, mnem: 'STD', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ld1 regD;tst16;stor16'},
  {op: 0xDE, mnem: 'LDU', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ftch16;tst16;st1 regU'},
  {op: 0xDF, mnem: 'STU', page: 0, mode: modes.direct | modes.bits16, code: 'drct;ld1 regU;tst16;stor16'},
  {op: 0xDE, mnem: 'LDS', page: 0x10, mode: modes.direct | modes.bits16, code: 'drct;ftch16;tst16;st1 regS'},
  {op: 0xDF, mnem: 'STS', page: 0x10, mode: modes.direct | modes.bits16, code: 'drct;ld1 regS;tst16;stor16'},

  {op: 0xE0, mnem: 'SUBB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;sub8;idxu;st1 regB'},
  {op: 0xE1, mnem: 'CMPB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;sub8;idxu'},
  {op: 0xE2, mnem: 'SBCB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;sbc8;idxu;st1 regB'},
  {
    op: 0xE3,
    mnem: 'ADDD',
    page: 0,
    mode: modes.indexed | modes.bits16,
    code: 'indx;ftch16;ld2 regD;add16;idxu;st1 regD',
  },
  {op: 0xE4, mnem: 'ANDB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;and8;idxu;st1 regB'},
  {op: 0xE5, mnem: 'BITB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;and8;idxu'},
  {op: 0xE6, mnem: 'LDB', page: 0, mode: modes.indexed, code: 'indx;ftch8;tst8;idxu;st1 regB'},
  {op: 0xE7, mnem: 'STB', page: 0, mode: modes.indexed, code: 'indx;ld1 regB;tst8;stor8;idxu'},
  {op: 0xE8, mnem: 'EORB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;eor8;idxu;st1 regB'},
  {op: 0xE9, mnem: 'ADCB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;adc8;idxu;st1 regB'},
  {op: 0xEA, mnem: 'ORB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;or8;idxu;st1 regB'},
  {op: 0xEB, mnem: 'ADDB', page: 0, mode: modes.indexed, code: 'indx;ftch8;ld2 regB;add8;idxu;st1 regB'},
  {op: 0xEC, mnem: 'LDD', page: 0, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;tst16;idxu;st1 regD'},
  {op: 0xED, mnem: 'STD', page: 0, mode: modes.indexed | modes.bits16, code: 'indx;ld1 regD;tst16;stor16;idxu'},
  {op: 0xEE, mnem: 'LDU', page: 0, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;tst16;idxu;st1 regU'},
  {op: 0xEF, mnem: 'STU', page: 0, mode: modes.indexed | modes.bits16, code: 'indx;ld1 regU;tst16;stor16;idxu'},
  {op: 0xEE, mnem: 'LDS', page: 0x10, mode: modes.indexed | modes.bits16, code: 'indx;ftch16;tst16;idxu;st1 regS'},
  {op: 0xEF, mnem: 'STS', page: 0x10, mode: modes.indexed | modes.bits16, code: 'indx;ld1 regS;tst16;stor16;idxu'},

  {op: 0xF0, mnem: 'SUBB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;sub8;st1 regB'},
  {op: 0xF1, mnem: 'CMPB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;sub8'},
  {op: 0xF2, mnem: 'SBCB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;sbc8;st1 regB'},
  {op: 0xF3, mnem: 'ADDD', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;ld2 regD;add16;st1 regD'},
  {op: 0xF4, mnem: 'ANDB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;and8;st1 regB'},
  {op: 0xF5, mnem: 'BITB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;and8'},
  {op: 0xF6, mnem: 'LDB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;tst8; st1 regB'},
  {op: 0xF7, mnem: 'STB', page: 0, mode: modes.extended, code: 'xtnd;ld1 regB;tst8;stor8'},
  {op: 0xF8, mnem: 'EORB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;eor8;st1 regB'},
  {op: 0xF9, mnem: 'ADCB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;adc8;st1 regB'},
  {op: 0xFA, mnem: 'ORB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;or8;st1 regB'},
  {op: 0xFB, mnem: 'ADDB', page: 0, mode: modes.extended, code: 'xtnd;ftch8;ld2 regB;add8;st1 regB'},
  {op: 0xFC, mnem: 'LDD', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;tst16;st1 regD'},
  {op: 0xFD, mnem: 'STD', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ld1 regD;tst16;stor16'},
  {op: 0xFE, mnem: 'LDU', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;tst16;st1 regU'},
  {op: 0xFF, mnem: 'STU', page: 0, mode: modes.extended | modes.bits16, code: 'xtnd;ld1 regU;tst16;stor16'},
  {op: 0xFE, mnem: 'LDS', page: 0x10, mode: modes.extended | modes.bits16, code: 'xtnd;ftch16;tst16;st1 regS'},
  {op: 0xFF, mnem: 'STS', page: 0x10, mode: modes.extended | modes.bits16, code: 'xtnd;ld1 regS;tst16;stor16'},

  {op: 0x01, mnem: 'FCB', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'FCC', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: '.FCC', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'FDB', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: '.WORD', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'DB', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: '.BYTE', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'DW', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'EQU', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: '=', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'FILL', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'ORG', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'RMB', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'DS', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'DIRECT', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'SETDP', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'CONST', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'VAR', page: 0, mode: modes.pseudo, code: ''},
  {op: 0x01, mnem: 'END', page: 0, mode: modes.pseudo, code: ''},

];

export {ops6809};
